- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: your-docker-image-name
        source: pull

    - name: Run Docker container
      docker_container:
        name: your-container-name
        image: your-docker-image-name
        ports:
          - "80:80"
        state: started
