name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Ensure this matches your directory structure

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform  # Ensure this matches your directory structure
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i "${{ steps.terraform.outputs.public_ip }}," ./ansible/playbook.yml --user ubuntu --private-key ${{ secrets.SSH_PRIVATE_KEY }}
