name: CI/CD Pipeline for Terraform, Ansible, and Docker

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch.
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the 'main' branch.

jobs:
  # Terraform Job
  terraform:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write  # Required for AWS credentials
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Output EC2 Instance IP
        id: terraform-output
        run: |
          echo "vm_ip=$(terraform output -raw vm_ip)" >> $GITHUB_OUTPUT

      - name: Debug EC2 Instance IP
        run: echo "EC2 Instance IP: ${{ steps.terraform-output.outputs.vm_ip }}"

  # Ansible Job
  ansible:
    runs-on: ubuntu-latest
    needs: terraform  # Ensures the Terraform job runs first
    permissions:
      id-token: write  # Required for AWS credentials
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Read EC2 Instance IP
        run: |
          echo "EC2 Instance IP: ${{ needs.terraform.outputs.vm_ip }}"

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Set up Ansible inventory file
        shell: bash
        run: |
          echo "[aws_servers]" > inventory.ini
          echo "${{ needs.terraform.outputs.vm_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=my-key-pair.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=publickey -o PasswordAuthentication=no'" >> inventory.ini

      - name: Debug Inventory File (optional)
        run: cat inventory.ini

      - name: Set up SSH private key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > my-key-pair.pem
          chmod 600 my-key-pair.pem  # Set permissions to read-only for the owner

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.ini deploy.yml
